language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "chaindora-test";' -U postgres

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: chaindora
  api_key:
    secure: "Ge8FCwpMGpD6BzrKL8+0XKn8uH78rIYKZVksq2FdO+LEURb5Vrwv8J4NYY4Ci2RFzisy7Ir8PiTfn+Ub8uxv4TgNyhyGwUL4XFpoPhkGcItnD2W3CsvnRhUuKPgUn15QJuyW/ex7TYlApyEuXO/TtujvqcxMw5Uq4MwQ5TbfY+wiBqjzwtrv0yMchrDnrskrUp4jaw2P3aTruAHcmzntZGIUWz0H3WMxVmm3a8WF/20iy785n4LLMmxUyxUiu7664j78dWvbe0WJAE7PFADsZ/rspM0D7Exiy5gpGDnp7sOT9jDwdJVTKNENvTw4X7G/xrqULlXnDr6NKJG7Ipx9BAmFpx0ajV+cdsnaJAbTfuVT5uVRi1QbEPFiI5iLsSUKfTuY+Hj1X4Ugdmv29mFcz/CMGXwYG/diisMhrL2KqPeYtZhqU/vkTboUJrXkRAeJJt9CRAxgQmCtBdAZ/U8rIoXNt0efmw7lfo3H6N4TCzWFc1loj20AP3S2S5l/EW8cpAqNIIQkZt3JIy+k692AinWuG2AwOCkTiDTuzfCtKmDrZ8kAAABuPGY0fQLwT/DYdrE3TIAkrDho3V9ba+uO75Asx0X/VGKdn8dlKDADthKO2OktLrFMp37sYo7Q1Js+P8fGCPJnRAZeKeJM0gEKv9IA7QJRuOcRC5rJP8n+T/E="
